-- SQL Setup Script for EventCall Supabase Migration
-- This script creates the necessary tables and relationships for the EventCall application.
-- It is designed to be run in the Supabase SQL editor.

-- 1. Create the Users table
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    branch VARCHAR(255),
    rank VARCHAR(255),
    role VARCHAR(255) NOT NULL DEFAULT 'user',
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Create the Events table
CREATE TABLE public.events (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    event_at TIMESTAMPTZ NOT NULL,
    location VARCHAR(255) NOT NULL,
    description TEXT,
    cover_image_url VARCHAR(255),
    ask_reason BOOLEAN NOT NULL DEFAULT FALSE,
    allow_guests BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_created_by FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE CASCADE
);

-- 3. Create the EventCustomQuestions table
CREATE TABLE public.event_custom_questions (
    id SERIAL PRIMARY KEY,
    event_id UUID NOT NULL,
    question_text VARCHAR(255) NOT NULL,
    question_type VARCHAR(50) NOT NULL DEFAULT 'text',
    options JSONB,
    CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE
);

-- 4. Create the RSVPs table
CREATE TABLE public.rsvps (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    event_id UUID NOT NULL,
    user_id BIGINT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    attending BOOLEAN NOT NULL,
    guest_count INTEGER DEFAULT 0,
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL
);

-- 5. Create the RSVPCustomAnswers table
CREATE TABLE public.rsvp_custom_answers (
    id SERIAL PRIMARY KEY,
    rsvp_id UUID NOT NULL,
    question_id INTEGER NOT NULL,
    answer_text TEXT NOT NULL,
    CONSTRAINT fk_rsvp_id FOREIGN KEY (rsvp_id) REFERENCES public.rsvps(id) ON DELETE CASCADE,
    CONSTRAINT fk_question_id FOREIGN KEY (question_id) REFERENCES public.event_custom_questions(id) ON DELETE CASCADE
);

-- Indexing Recommendations
CREATE INDEX ON public.events (created_by);
CREATE INDEX ON public.event_custom_questions (event_id);
CREATE INDEX ON public.rsvps (event_id);
CREATE INDEX ON public.rsvps (user_id);
CREATE INDEX ON public.rsvp_custom_answers (rsvp_id);
CREATE INDEX ON public.rsvp_custom_answers (question_id);
CREATE INDEX ON public.users (username);
CREATE INDEX ON public.users (email);
CREATE INDEX ON public.events (event_at);
CREATE INDEX ON public.rsvps (email);

-- Grant usage on the new tables to the Supabase roles
GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
